/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import com.opencsv.CSVReader;
import java.awt.List;
import java.io.File;
import java.io.FileFilter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Danial
 */
public class JTableTut extends javax.swing.JFrame {

    private File openedFile; 
    private String[] header;
    private Vector<Vector<String>> data = new Vector<>(); 
    private Vector headerVec = new Vector();
    private boolean loaded = false; 
    private File outputFile; 
    
    /**
     * Creates new form JTableTut
     */
    public JTableTut() {        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileExplorer = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        fileNameTextField = new javax.swing.JTextField();
        browseFileExplorerButton = new javax.swing.JButton();
        selectFile = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        columnTextArea = new javax.swing.JTextArea();
        columnComboBox = new javax.swing.JComboBox<String>();
        displayButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        csvTable = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column) {
                return false;
            };
        };
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numClustersTextField = new javax.swing.JTextField();
        numIterationsTextField = new javax.swing.JTextField();
        generateButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        outputFileTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        generatedScalaTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNameTextFieldActionPerformed(evt);
            }
        });

        browseFileExplorerButton.setText("Browse");
        browseFileExplorerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseFileExplorerButtonActionPerformed(evt);
            }
        });

        selectFile.setText("Select");
        selectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFileActionPerformed(evt);
            }
        });

        columnTextArea.setColumns(20);
        columnTextArea.setRows(5);
        jScrollPane2.setViewportView(columnTextArea);

        displayButton.setText("Display");
        displayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Column:");

        csvTable.setModel(new javax.swing.table.DefaultTableModel(
            data,
            headerVec
        ));
        csvTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane3.setViewportView(csvTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(browseFileExplorerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fileNameTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selectFile)
                        .addGap(630, 630, 630))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                        .addComponent(columnComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(displayButton)))
                                .addGap(630, 630, 630))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3)
                                .addContainerGap())))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseFileExplorerButton)
                    .addComponent(selectFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(columnComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(displayButton))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Source and Datasets", jPanel2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Configurations");

        jLabel2.setText("Clusters:");

        jLabel3.setText("Iterations:");

        generateButton.setText("Generate");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Output File:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(generateButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(outputFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numIterationsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numClustersTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 1005, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(200, 200, 200)
                        .addComponent(jLabel2))
                    .addComponent(numClustersTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(numIterationsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(outputFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 331, Short.MAX_VALUE)
                .addComponent(generateButton)
                .addContainerGap())
        );

        jTabbedPane1.addTab("K-Means Clustering", jPanel1);

        generatedScalaTextArea.setColumns(20);
        generatedScalaTextArea.setRows(5);
        jScrollPane1.setViewportView(generatedScalaTextArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Generated Code", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayButtonActionPerformed
        if (!loaded) {
            columnTextArea.setText("Please select a file");
        }
        else {
            int colIndex = columnComboBox.getSelectedIndex();
            printColumnData(header, data, colIndex);
        }
        
        
    }//GEN-LAST:event_displayButtonActionPerformed

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        int numClusters = Integer.parseInt(numClustersTextField.getText());
        int numIterations = Integer.parseInt(numIterationsTextField.getText());
        if (!loaded) {
            generatedScalaTextArea.setText("Please select a file");
        }
        else {
            int colIndex = columnComboBox.getSelectedIndex();
            if(numClusters <= 0){
                generatedScalaTextArea.append("NUMBER OF CLUSTERS CANNOT BE 0 OR LESS.");
            }
            else if(numIterations <= 0){
                generatedScalaTextArea.append("NUMBER OF ITERATIONS CANNOT BE 0 OR LESS.");
            }
            else{
                String outputFileName = outputFileTextField.getText();
                createFile(colIndex, outputFileName);
                generateScalaCode(numClusters, numIterations);
            }
        }
    }//GEN-LAST:event_generateButtonActionPerformed

    private void browseFileExplorerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseFileExplorerButtonActionPerformed
        //fileExplorer.addChoosableFileFilter(new FileNameExtensionFilter("CSV Files", "csv"));
        fileExplorer.setAcceptAllFileFilterUsed(false);
        fileExplorer.setFileFilter(new FileNameExtensionFilter("CSV Files", "csv"));

        int returnVal = fileExplorer.showOpenDialog(JTableTut.this);
        //TODO: Verify for only a .csv file
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            openedFile = fileExplorer.getSelectedFile();
            fileNameTextField.setText(openedFile.getAbsolutePath());
            System.out.println("User chose: " + openedFile.getName());
        } else {
            System.out.println("User clicked cancelled");
        }
    }//GEN-LAST:event_browseFileExplorerButtonActionPerformed

    private void selectFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFileActionPerformed
        String fileName = openedFile.getAbsolutePath();
        saveData(fileName);
        loaded = true;
    }//GEN-LAST:event_selectFileActionPerformed

    private void fileNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileNameTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JTableTut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JTableTut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JTableTut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JTableTut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JTableTut().setVisible(true);
            }
        });
    }
    
    public void saveData(String fileName) {
        if (loaded == true) {
            header = null;
            data.clear();
            headerVec.clear();
        } 
        
        String[] row = null;
        
        int rowCounter = 0; 
        
        columnTextArea.setText(""); 
        try {
            CSVReader reader = new CSVReader(new FileReader(fileName)); 
            header = reader.readNext();
            
            for (String col: header) {
                columnTextArea.append(col.toUpperCase() + "   ");
                headerVec.add(col.toUpperCase());
            }
            
            columnTextArea.append("\n"); 
            
            while((row = reader.readNext()) != null) {
                data.add(new Vector<String>());
                for(int i =0; i < row.length; i++) {
                    data.get(rowCounter).add(row[i]); 
                }
                rowCounter++; 
            }
            reader.close(); 
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JTableTut.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JTableTut.class.getName()).log(Level.SEVERE, null, ex);
        }
        csvTable.setModel(new javax.swing.table.DefaultTableModel(
                data,
                headerVec
                ));
        
        //printAllData(data);
        printColumnData(header, data, 0); 
        updateComboBox(header);
    }
    
    public void printAllData(ArrayList<ArrayList<String>> data) {
        for (int i=0; i<data.size(); i++) {
           for (int j=0; j<data.get(i).size(); j++) {
               columnTextArea.append(data.get(i).get(j) + "    ");
           }
           columnTextArea.append("\n"); 
        }
    }
    
    public void printColumnData(String[] header, Vector<Vector<String>> data, int colNumber) {
        columnTextArea.setText(header[colNumber].toUpperCase() + "\n"); 
        for (int i = 0; i < data.size(); i++) {
            columnTextArea.append(data.get(i).get(colNumber) + "\n"); 
        }
    }
    
    public void updateComboBox(String[] header) {
        for (String x: header) {
            columnComboBox.addItem(x.toUpperCase()); 
        }
    }
    
    public void createFile(int colIndex, String outputFileName) {
        try { 
            outputFile = new File(outputFileName + ".txt");
            PrintWriter writer = new PrintWriter(outputFile); 
            for(int i = 0; i < data.size(); i++) {
                writer.println(data.get(i).get(colIndex));
            }
            writer.close(); 
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JTableTut.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void generateScalaCode(int clu, int ite) {
        String generatedCode; 
        String path = outputFile.getAbsolutePath().replaceAll("\\\\", "/");
        
        generatedCode = "import org.apache.spark.mllib.clustering.{KMeans, KMeansModel}\n" +
                "\nimport org.apache.spark.mllib.linalg.Vectors\n\n" +
                "val data = sc.textFile(\"" + path + "\")\n" +
                "val parsedData = data.map(s => Vectors.dense(s.split(' ').map(_.toDouble))).cache()\n\n" +
                "val numClusters = " + clu + "\n" +
                "val numIterations = " + ite + "\n" +
                "val clusters = KMeans.train(parsedData, numClusters, numIterations)\n\n" +
                "val WSSE = clusters.computeCost(parsedData)\n" +
                "println(\"Within Set Sum of Squared Errors = \" + WSSE)\n" + 
                "clusters.save(sc, \"myModelPath\")\n" +
                "val sameModel = KMeansModel.load(sc, \"myModelPath\")\n\n";
        
        generatedScalaTextArea.setText(generatedCode); 
    }
   
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseFileExplorerButton;
    private javax.swing.JComboBox<String> columnComboBox;
    private javax.swing.JTextArea columnTextArea;
    private javax.swing.JTable csvTable;
    private javax.swing.JButton displayButton;
    private javax.swing.JFileChooser fileExplorer;
    private javax.swing.JTextField fileNameTextField;
    private javax.swing.JButton generateButton;
    private javax.swing.JTextArea generatedScalaTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField numClustersTextField;
    private javax.swing.JTextField numIterationsTextField;
    private javax.swing.JTextField outputFileTextField;
    private javax.swing.JButton selectFile;
    // End of variables declaration//GEN-END:variables
        
}
